### ISSUE TITLE
Images not loading due to request timeout

### ISSUE THREAD

**Issue by NoFearJoe** [RedMadRobot/figma-export#57] opened 2020-12-23 08:21 UTC
We have about 120 images and when we try to export them the request fails due to timeout.
We tried to change the timeout in FigmaClient to 600, but got this error: `Unexpectedly found nil while implicitly unwrapping an Optional value: file FigmaAPI/FigmaClient.swift, line 26`.

We are using the latest version of figma-export (0.18.5).

**Comment by subdan** [comment] 2020-12-23 08:26
I'll check it and get back to you tonight.

**Comment by subdan** [comment] 2020-12-23 08:42
Try to change `batchSize` value from 100 to 20 in `ImagesLoader.swift` line 176.

**Comment by DevFirts** [comment] 2020-12-23 09:26
Hello @subdan
I change the `batchSize` to 20 but the problem remains. It looks like the call `.map { try figmaClient.request($0) }` is hanging in `ImagesLoader#loadComponents`

**Comment by subdan** [comment] 2020-12-23 09:38
To fix this issue I need to reproduce it. I will create an example Figma file with 120 images and try to export it. I will do it by the end of the week and get back to you.

**Comment by subdan** [comment] 2020-12-25 16:24
I've exported 242 image components (726 PNG images) using FigmaExport without any issues.

Possible issues:
1. You have some complex images that Figma unable to exports and throws an error.
2. You have big images for which Figma takes a long time to convert.

Could you show me the complex and the big one image you try to export?
Which type of image do you try to export: raster or vector?
What is the output format: PDF of PNG?

Possible solution:
1. Try to export only 20 images. Is it succeed?
2. Add another 20 images to your team library and try to export again.
3. Repeat and find bad images.

If it is possible I can try to export your images if you give me access to your Figma File.

**Comment by osipxd** [comment] 2021-01-11 11:52
Maybe this issue fixed with #60?

**Comment by subdan** [comment] 2021-01-11 11:56
@osipxd Maybe.

I've just released [0.18.8](https://github.com/RedMadRobot/figma-export/releases/tag/0.18.8) where I add timeout property to config file. See [CONFIG.md](https://github.com/RedMadRobot/figma-export/blob/master/CONFIG.md) for more info.

@NoFearJoe, @DevFirts Please, update FigmaExport, change timeout property and try to export images again.

**Comment by DevFirts** [comment] 2021-02-09 09:21
I left only two images in the frame, but still when using FigmaExport an error occurs `The request timed out.`  or `Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value: file FigmaAPI/Client.swift, line 33`
at the same time requests made via postman are processed quickly (~ 3 sec.)

We are using the latest version of figma-export (0.18.9).
format: png
timeout: 60 sec

**Comment by subdan** [comment] 2021-02-09 12:54
Could you please give me access to your Figma file?

**Comment by NoFearJoe** [comment] 2021-02-19 12:25
#75

**Comment by subdan** [comment] 2021-03-04 08:03
Fixed in [0.21.1](https://github.com/RedMadRobot/figma-export/releases/tag/0.21.1) via #75

**Closed by subdan** 2021-03-04 08:03 UTC
Labels: question
